trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'
  demands:
    - npm

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.100'
  inputs:
    version: 3.1.100

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'

タスク: DotNetCoreCLI@2表示名: 'プロジェクトを公開 - リリース' 入力: コマンド: '発行' プロジェクト: '発行' プロジェクト: '**/*.csproj' publishWebProjects: 偽引数: '--ビルドなし --構成リリース --出力 $(ビルド.アーティファクトステージングディレクトリ)/リリース' zipAfterPublish: true -タスク: PublishBuildArtifacts@1表示名: 'アーティファクトの公開: ドロップ' 条件: 成功()